controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

annotation_index:
  path: /
  controller: App\Controller\AnnotationController::index
